#!/bin/bash
###############################################################
## AUTHOR Name: Boyang Yan                                   ##
## KEYWORDs: Start-up all of system set-up                   ##
## PURPOSE: Management package and Dot configureation        ##
## ENVIRONment: mac, Linux                                   ##
## COMMENTs:                                                 ##
## Last Modified Date: 25.09.2021                            ##
###############################################################

## pull latest of all git submodules
git submodule update --recursive --remote
## Install System packages
make basePackages
make pythonPackages
make emacspackages
make multimediaPackages
make cloudVirtualPackages
