#!/bin/bash
###############################################################
## AUTHOR Name: Boyang Yan                                   ##
## KEYWORDs: Start-up all of system set-up                   ##
## PURPOSE: Management package and Dot configureation        ##
## ENVIRONment: mac, Linux                                   ##
## COMMENTs:                                                 ##
## Last Modified Date: 25.09.2021                            ##
###############################################################

## pull latest of all git submodules
#git submodule update --recursive --remote

# Install System packages
read -p "Do you want to check/install requied packages (Y/n)? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]; then
    source $PWD/packageInstall/installPackage
fi

#make execs
#sh ./Scripts/init
