#!/bin/sh
###############################################################
## AUTHOR Name: Boyang Yan                                   ##
## KEYWORDs: ZSH start-up setup                              ##
## PURPOSE: Set-up System                                    ##
## ENVIRONment: mac, Linux                                   ##
## COMMENTs:                                                 ##
## Last Modified Date: 26.09.2021                            ##
###############################################################
echo "Start Set-up Doom Emacs"
rm -rf ~/.emacs.d
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
ln -vsf $PWD/doom ~/.config/doom
cd ~/.emacs.d
git checkout develop
~/.emacs.d/bin/doom install
echo "Set-up Doom Emacs Done"
