#!/bin/sh
###############################################################
## AUTHOR Name: Boyang Yan                                   ##
## KEYWORDs: Nerd Fonts setup                                ##
## PURPOSE: Set-up Nerd Fonts for Linux/Mac System           ##
## ENVIRONment: mac, Linux                                   ##
## COMMENTs:                                                 ##
## Last Modified Date: 06.10.2021                            ##
###############################################################
echo "Start Set-up Nerd Fonts"
if [[ "$OSTYPE" == "linux-gnu"* ]] || [[ "$OSTYPE" == "darwin"* ]]; then
   sudo git config --system core.longpaths true
   git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git ~/nerdFonts
   sh ~/nerdFonts/install.sh
   rm -rf ~/nerdFonts
fi
echo "Set-up Nerd Font Done"

echo "Install material design icons"

sudo pkgfile --update
yay -S --needed --noconfirm ttf-material-design-icons
