#!/bin/sh
###############################################################
## AUTHOR Name: Boyang Yan                                   ##
## KEYWORDs: Nerd Fonts setup                                ##
## PURPOSE: Set-up Nerd Fonts for Linux/Mac System           ##
## ENVIRONment: mac, Linux                                   ##
## COMMENTs:                                                 ##
## Last Modified Date: 06.10.2021                            ##
###############################################################
echo "Start Set-up Nerd Fonts"
if [[ "$OSTYPE" == "linux-gnu"* ]] || [[ "$OSTYPE" == "darwin"* ]]; then
   sudo git config --system core.longpaths true
   git clone --branch 2.1.0 https://github.com/ryanoasis/nerd-fonts.git ~/nerdFonts
   cd ~/nerdFonts
   ./install.sh
   rm -rf ~/nerdFonts
fi
echo "Set-up Nerd Font Done"
