#!/bin/bash
# Bash Menu Script
###############################################################
## AUTHOR Name: Boyang Yan                                   ##
## KEYWORDs: Init set-up Menu                                ##
## PURPOSE: Init Set-up Menu to call others init script      ##
## ENVIRONment: mac, Linux                                   ##
## COMMENTs:                                                 ##
## Last Modified Date: 06.10.2021                            ##
###############################################################

echo "Let's we start init set-up our system"

MKDIR = "mkdir -p"
LN = "ln -vsf"
SLN = "sudo ln -vsf"
LNDIR = "ln -vs"

PS3='Please enter your choice: '
options=("All" "ZSH" "Doom Emacs" "Nerd Fonts" "Blog" "NPM" "Mail" "Password" "PIP" "GIT" "PICOM" "NVIM" "TEAMS" "WM" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "All")
            echo "Run All"
            ;;&
        "All"|"ZSH")
            sh $PWD/Scripts/zshSetUp
            ;;&
        "All"|"Doom Emacs")
            mkdir ~/org/org-roam
            sh $PWD/Scripts/doomEmacs
            ;;&
        "All"|"Nerd Fonts")
            sh $PWD/Scripts/front
            ;;&
        "All"|"Blog")
            ln -vsf $PWD/blog/ ~/
            ;;&
        "All"|"NPM")
            sh $PWD/Scripts/npm
            ;;&
        "All"|"Mail")
            sh $PWD/Scripts/mail
            ;;&
        "All"|"Password")
            ln -vsf $PWD/password ~/.config/
            ;;&
        "All"|"PIP")
            sh $PWD/Scripts/pip
            ;;&
        "All"|"GIT")
            sh $PWD/Scripts/git
	    ;;&
    	"ALL"|"PICOM")
	    mkdir $HOME/.config/picom/
	    ln -vsf $PWD/picom/picom.conf $HOME/.config/picom/picom.conf
	    ;;&
	"ALL"|"NVIM")
            sh $PWD/Scripts/nvim
	    ;;&
	"ALL"|"TEAMS")
	    sh $PWD/Scripts/teams
	    ;;&
	"ALL"|"WM")
	    sh $PWD/../metaWM/setupWM
	    ;;&
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
