#!/bin/bash
# Bash Menu Script
###############################################################
## AUTHOR Name: Boyang Yan                                   ##
## KEYWORDs: Init set-up Menu                                ##
## PURPOSE: Init Set-up Menu to call others init script      ##
## ENVIRONment: mac, Linux                                   ##
## COMMENTs:                                                 ##
## Last Modified Date: 06.10.2021                            ##
###############################################################

echo "Let's we start init set-up our system"

PS3='Please enter your choice: '
options=("All" "ZSH" "Doom Emacs" "Nerd Fonts" "Blog" "NPM" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "All")
            echo "Run All"
            ;;&
        "All"|"ZSH")
            sh $PWD/Scripts/zshSetUp
            ;;
        "All"|"Doom Emacs")
            sh $PWD/Scripts/doomEmacs
            ;;
        "All"|"Nerd Fonts")
            sh $PWD/Scripts/front
            ;;
        "All"|"Blog")
            ln -vsf $PWD/blog/ ~/blog/
            ;;
        "All"|"NPM")
            sh $PWD/Scripts/npm
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
