#!/bin/bash
# Bash Menu Script
#######################################################################
## AUTHOR Name: Boyang Yan                                           ##
## KEYWORDs: Install all of needed PIP package for this system       ##
## PURPOSE: Install all of needed PIP package for this system        ##
## ENVIRONment: mac, Linux                                           ##
## COMMENTs:                                                         ##
## Last Modified Date: 31.10.2021                                    ##
#######################################################################

echo "Let's we install all of required PIP's package for our system"

pip install isort
pip install pipenv
