#!/bin/sh
###############################################################
## AUTHOR Name: Boyang Yan                                   ##
## KEYWORDs: docker                                          ##
## PURPOSE: Install and set-up docker on Arch Linux          ##
## ENVIRONment: mac, Linux                                   ##
## COMMENTs:                                                 ##
## Last Modified Date: 03.03.2022                            ##
###############################################################

sudo pacman --noconfirm -S --needed - < $HOME/DotFiles/ArchLinux/R/pacmanList
# https://unix.stackexchange.com/questions/31283/error-in-r-unable-to-open-connection-to-x11

docker run --rm -e DISABLE_AUTH=true -v "$HOME":/home/rstudio/ -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -p 8787:8787 rocker/verse
